all: main.exe historial.exe leer-historial.exe

main.exe: main.cpp
	g++ -o main.exe main.cpp

historial.exe: historial.cpp
	g++ -o historial.exe historial.cpp

leer-historial.exe: leer-historial.cpp
	g++ -o leer-historial.exe leer-historial.cpp


